from .assurland import AssurlandScraping
from .ffa import FfaScraping
from .l_agefi import AgefiScraping
from .l_obs import ObsScraping
from .le_figaro import LeFigaroScraping
from .le_monde import LeMondeScraping
from .marianne import MarianneScraping
from .ouest_france import OuestFranceScraping
from .risques import RisquesScraping
from .tribune_assurance import TribuneAssuranceScraping
from .universite_assurance import UniversiteAssuranceScraping
